package com.kii.cloud.rest.client.model.servercode;

import static org.junit.Assert.assertEquals;

import org.junit.Test;
import org.junit.runner.RunWith;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.kii.cloud.rest.client.SkipAcceptableTestRunner;
import com.kii.cloud.rest.client.model.servercode.KiiServerHookConfiguration;

@RunWith(SkipAcceptableTestRunner.class)
public class KiiServerHookConfigurationTest {
	@Test
	public void deserializeUserTriggerTest() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("{" + "\n");
		sb.append("    \"kiicloud://users\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"USER_CREATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"userCreated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://users\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"USER_EMAIL_VERIFIED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"userEmailVerified\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://users\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"USER_PHONE_VERIFIED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"userPhoneVerified\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://users\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"USER_PASSWORD_RESET_COMPLETED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"userPasswordResetCompleted\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://users\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"USER_PASSWORD_CHANGED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"userPasswordChanged\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://users\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"USER_DELETED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"userDeleted\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://users\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"USER_UPDATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"userUpdated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]" + "\n");
		sb.append("}" + "\n");
		JsonObject source = (JsonObject)new JsonParser().parse(sb.toString());
		KiiServerHookConfiguration conf = new KiiServerHookConfiguration(source);
		JsonObject dest = conf.toJson();
		assertEquals(source, dest);
	}
	@Test
	public void deserializeGroupTriggerTest() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("{" + "\n");
		sb.append("    \"kiicloud://groups\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"GROUP_CREATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"groupCreated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://groups\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"GROUP_DELETED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"groupDeleted\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://groups\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"GROUP_MEMBERS_ADDED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"groupMembersAdded\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://groups\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"GROUP_MEMBERS_REMOVED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"groupMembersRemoved\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]" + "\n");
		sb.append("}" + "\n");
		JsonObject source = (JsonObject)new JsonParser().parse(sb.toString());
		KiiServerHookConfiguration conf = new KiiServerHookConfiguration(source);
		JsonObject dest = conf.toJson();
		assertEquals(source, dest);
	}
	@Test
	public void deserializeInstallationTriggerTest() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("{" + "\n");
		sb.append("    \"kiicloud://installations\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"INSTALLATION_CREATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"installationCreated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://installations\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"INSTALLATION_DELETED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"installationDeleted\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]" + "\n");
		sb.append("}" + "\n");
		JsonObject source = (JsonObject)new JsonParser().parse(sb.toString());
		KiiServerHookConfiguration conf = new KiiServerHookConfiguration(source);
		JsonObject dest = conf.toJson();
		assertEquals(source, dest);
	}
	@Test
	public void deserializeBucketTriggerTest() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("{" + "\n");
		sb.append("    \"kiicloud://buckets/app_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_CREATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectCreated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://buckets/app_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_DELETED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectDeleted\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://buckets/app_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_UPDATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectUpdated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://groups/*/buckets/group_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_CREATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectCreated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://groups/*/buckets/group_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_DELETED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectDeleted\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://groups/*/buckets/group_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_UPDATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectUpdated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://users/*/buckets/user_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_CREATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectCreated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://users/*/buckets/user_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_DELETED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectDeleted\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://users/*/buckets/user_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_UPDATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectUpdated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://things/*/buckets/thing_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_CREATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectCreated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://things/*/buckets/thing_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_DELETED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectDeleted\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]," + "\n");
		sb.append("    \"kiicloud://things/*/buckets/thing_bucket\": [" + "\n");
		sb.append("        {" + "\n");
		sb.append("            \"when\"    : \"DATA_OBJECT_UPDATED\"," + "\n");
		sb.append("            \"what\"    : \"EXECUTE_SERVER_CODE\"," + "\n");
		sb.append("            \"endpoint\": \"dataObjectUpdated\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    ]" + "\n");
		sb.append("}" + "\n");
		JsonObject source = (JsonObject)new JsonParser().parse(sb.toString());
		KiiServerHookConfiguration conf = new KiiServerHookConfiguration(source);
		JsonObject dest = conf.toJson();
		assertEquals(source, dest);
	}
	@Test
	public void deserializeSchedulerTriggerTest() throws Exception {
		StringBuilder sb = new StringBuilder();
		sb.append("{" + "\n");
		sb.append("    \"kiicloud://scheduler\": {" + "\n");
		sb.append("        \"daily_batch\": {" + "\n");
		sb.append("            \"cron\": \"1 0 * * *\"," + "\n");
		sb.append("            \"endpoint\": \"daily_batch_function\"," + "\n");
		sb.append("            \"parameters\": {" + "\n");
		sb.append("                \"args1\": 10," + "\n");
		sb.append("                \"args2\": true" + "\n");
		sb.append("            }," + "\n");
		sb.append("            \"what\": \"EXECUTE_SERVER_CODE\"" + "\n");
		sb.append("        }," + "\n");
		sb.append("        \"weekly_batch\": {" + "\n");
		sb.append("            \"cron\": \"0 0 30 * *\"," + "\n");
		sb.append("            \"endpoint\": \"weekly_batch_function\"," + "\n");
		sb.append("            \"parameters\": {" + "\n");
		sb.append("            }," + "\n");
		sb.append("            \"what\": \"EXECUTE_SERVER_CODE\"" + "\n");
		sb.append("        }" + "\n");
		sb.append("    }" + "\n");
		sb.append("}" + "\n");
		JsonObject source = (JsonObject)new JsonParser().parse(sb.toString());
		KiiServerHookConfiguration conf = new KiiServerHookConfiguration(source);
		JsonObject dest = conf.toJson();
		assertEquals(source, dest);
	}
}
